### ISSUE TITLE
dist.zip does not work properly

### ISSUE THREAD

**Issue by nnn1590** [nnn1590/KirbyGame-Java#1]
https://github.com/nnn1590/KirbyGame-Java/blob/6cbd5a4f43497c2bd87ead1e9698d06895f48ad6/src/main/java/Kirby/KirbyGame.java#L544-L546
```java
map = new TiledMap("kirbymap.tmx","src/main/resources");
```
is almost the same.

`./gradlew run` works properly.

But
```bash
./gradlew distzip
cd $(mktemp -d Kirby-XXXXXX -p /tmp)
unzip "${OLDPWD}/build/distributions/Kirby.zip"
Kirby/bin/Kirby

cd -
rm -r ${OLDPWD}
```
doesn't work.

<details>
<summary>Error log</summary>

```
ERROR:Resource not found: src/main/resources/kirbyterrain.png
java.lang.RuntimeException: Resource not found: src/main/resources/kirbyterrain.png
	at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
	at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:185)
	at org.newdawn.slick.Image.<init>(Image.java:192)
	at org.newdawn.slick.tiled.TileSet.<init>(TileSet.java:124)
	at org.newdawn.slick.tiled.TiledMap.load(TiledMap.java:661)
	at org.newdawn.slick.tiled.TiledMap.<init>(TiledMap.java:122)
	at Kirby.KirbyGame.level1Setup(KirbyGame.java:545)
	at Kirby.KirbyGame.initStatesList(KirbyGame.java:350)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:164)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317)
	at Kirby.KirbyGame.main(KirbyGame.java:557)
Fri Jan 31 23:22:11 JST 2020 ERROR:Failed to parse tilemap
org.newdawn.slick.SlickException: Failed to parse tilemap
	at org.newdawn.slick.tiled.TiledMap.load(TiledMap.java:695)
	at org.newdawn.slick.tiled.TiledMap.<init>(TiledMap.java:122)
	at Kirby.KirbyGame.level1Setup(KirbyGame.java:545)
	at Kirby.KirbyGame.initStatesList(KirbyGame.java:350)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:164)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317)
	at Kirby.KirbyGame.main(KirbyGame.java:557)
Caused by: java.lang.RuntimeException: Resource not found: src/main/resources/kirbyterrain.png
	at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
	at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:185)
	at org.newdawn.slick.Image.<init>(Image.java:192)
	at org.newdawn.slick.tiled.TileSet.<init>(TileSet.java:124)
	at org.newdawn.slick.tiled.TiledMap.load(TiledMap.java:661)
	... 7 more
```
</details>

**Comment by nnn1590** [comment]
If `kirbyterrain.png` is in the current directory with `map = new TiledMap("kirbymap.tmx",".");`, it will work properly
```bash
./gradlew distzip
cd $(mktemp -d Kirby-XXXXXX -p /tmp)
unzip "${OLDPWD}/build/distributions/Kirby.zip"
cd Kirby/lib
../bin/Kirby
```
